# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Home"
#   url = "#about"
#   weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20
  pre = "<i class='fas fa-check'></i>&nbsp;"

# [[main]]
#   name = "Experience"
#   url = "#experience"
#   weight = 30

[[main]]
  name = "Certificates"
  url = "#accomplishments"
  weight = 40
  pre = "<i class='fas fa-award'></i>&nbsp;"

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 50

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 60
  pre = "<i class='fas fa-code'></i>&nbsp;"

# [[main]]
#   name = "Events"
#   url = "#events"
#   weight = 70

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 80

[[main]]
  name = "Tags"
  url = "#tags"
  weight = 90
  pre = "<i class='fas fa-tags'></i>&nbsp;"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100
  pre = "<i class='fas fa-envelope'></i>&nbsp;"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 110
