# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "#about"
  weight = 10

# [[main]]
#   name = "Habilidades"
#   url = "#skills"
#   weight = 20

# [[main]]
#   name = "Experiencia"
#   url = "#experience"
#   weight = 30

[[main]]
  name = "Logros"
  url = "#accomplishments"
  weight = 40

# [[main]]
#   name = "Entradas de Blog"
#   url = "#posts"
#   weight = 50

[[main]]
  name = "Proyectos"
  url = "#projects"
  weight = 60

# [[main]]
#   name = "Charlas"
#   url = "#talks"
#   weight = 70

# [[main]]
#   name = "Publicaciones"
#   url = "#featured"
#   weight = 80

[[main]]
  name = "Etiquetas"
  url = "#tags"
  weight = 90

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 110
